//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfa_casScolaireDepart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_resultat
    {
        public string no_cours { get; set; }
        public string no_da { get; set; }
        public string session { get; set; }
        public Nullable<short> note { get; set; }
    
        public virtual tbl_cours tbl_cours { get; set; }
        public virtual tbl_etudiant tbl_etudiant { get; set; }
    }
}
