//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfa_casScolaireDepart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cours()
        {
            this.tbl_resultat = new HashSet<tbl_resultat>();
            this.tbl_cours1 = new HashSet<tbl_cours>();
            this.tbl_cours2 = new HashSet<tbl_cours>();
        }
    
        public string no_cours { get; set; }
        public string nom_cours { get; set; }
        public string pond { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_resultat> tbl_resultat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cours> tbl_cours1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cours> tbl_cours2 { get; set; }
    }
}
