//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfa_casScolaireDepart
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueEtudiantNoteAnglai
    {
        public string ID { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string course_number { get; set; }
        public string course_name { get; set; }
        public string session { get; set; }
        public Nullable<short> rating { get; set; }
    }
}
