//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfa_casScolaireDepart
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueNoteEtudiant
    {
        public string ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Numéro_de_cours { get; set; }
        public string Nom_cours { get; set; }
        public string session { get; set; }
        public Nullable<short> Note { get; set; }
    }
}
